version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: virtual-it-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - virtual-it-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: virtual-it-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - virtual-it-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtual-it-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/virtual-it-company?authSource=admin
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-super-secret-key-change-in-production
    depends_on:
      - mongodb
      - redis
    networks:
      - virtual-it-network
    volumes:
      - ./uploads:/app/uploads

  # Nginx Reverse Proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: virtual-it-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - app
    networks:
      - virtual-it-network
    profiles:
      - production

volumes:
  mongodb_data:
  redis_data:

networks:
  virtual-it-network:
    driver: bridge